[2025-05-02T00:08:26.190+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-02T00:08:26.232+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_demo.transform_data_2 manual__2025-05-02T00:08:18.824723+00:00 [queued]>
[2025-05-02T00:08:26.241+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_demo.transform_data_2 manual__2025-05-02T00:08:18.824723+00:00 [queued]>
[2025-05-02T00:08:26.244+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-02T00:08:26.285+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data_2> on 2025-05-02 00:08:18.824723+00:00
[2025-05-02T00:08:26.293+0000] {standard_task_runner.py:63} INFO - Started process 1239 to run task
[2025-05-02T00:08:26.299+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_demo', 'transform_data_2', 'manual__2025-05-02T00:08:18.824723+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmppn7gi64s']
[2025-05-02T00:08:26.304+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask transform_data_2
[2025-05-02T00:08:26.344+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-02T00:08:26.390+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_demo.transform_data_2 manual__2025-05-02T00:08:18.824723+00:00 [running]> on host b3f0d5cbc6df
[2025-05-02T00:08:26.550+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_demo' AIRFLOW_CTX_TASK_ID='transform_data_2' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T00:08:18.824723+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-02T00:08:18.824723+00:00'
[2025-05-02T00:08:26.551+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-02T00:08:26.598+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-02T00:08:26.599+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-02T00:08:26.610+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_pipeline_demo, task_id=transform_data_2, run_id=manual__2025-05-02T00:08:18.824723+00:00, execution_date=20250502T000818, start_date=20250502T000826, end_date=20250502T000826
[2025-05-02T00:08:26.673+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-02T00:08:26.701+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-02T00:08:26.756+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
