[2025-04-17T21:17:54.489+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-17T21:17:54.504+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_demo.download_data manual__2025-04-17T21:17:52.464084+00:00 [queued]>
[2025-04-17T21:17:54.513+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_demo.download_data manual__2025-04-17T21:17:52.464084+00:00 [queued]>
[2025-04-17T21:17:54.519+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-17T21:17:54.548+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_data> on 2025-04-17 21:17:52.464084+00:00
[2025-04-17T21:17:54.557+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_demo', 'download_data', 'manual__2025-04-17T21:17:52.464084+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpb8q6rzbu']
[2025-04-17T21:17:54.554+0000] {standard_task_runner.py:63} INFO - Started process 756 to run task
[2025-04-17T21:17:54.561+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask download_data
[2025-04-17T21:17:54.592+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-17T21:17:54.638+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_demo.download_data manual__2025-04-17T21:17:52.464084+00:00 [running]> on host b3f0d5cbc6df
[2025-04-17T21:17:54.762+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_demo' AIRFLOW_CTX_TASK_ID='download_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T21:17:52.464084+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-17T21:17:52.464084+00:00'
[2025-04-17T21:17:54.763+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-17T21:17:55.404+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-17T21:17:55.405+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 12, in download_data
    with open(LOCAL_PATH, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/winequallity.csv'
[2025-04-17T21:17:55.417+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=data_pipeline_demo, task_id=download_data, run_id=manual__2025-04-17T21:17:52.464084+00:00, execution_date=20250417T211752, start_date=20250417T211754, end_date=20250417T211755
[2025-04-17T21:17:55.448+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task download_data ([Errno 2] No such file or directory: '/data/winequallity.csv'; 756)
[2025-04-17T21:17:55.462+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-17T21:17:55.485+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-17T21:17:55.502+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
