[2025-05-01T21:16:31.262+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-01T21:16:31.313+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_demo.transform_data_2 manual__2025-05-01T21:16:23.234657+00:00 [queued]>
[2025-05-01T21:16:31.328+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_demo.transform_data_2 manual__2025-05-01T21:16:23.234657+00:00 [queued]>
[2025-05-01T21:16:31.333+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-01T21:16:31.363+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data_2> on 2025-05-01 21:16:23.234657+00:00
[2025-05-01T21:16:31.371+0000] {standard_task_runner.py:63} INFO - Started process 404 to run task
[2025-05-01T21:16:31.379+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_demo', 'transform_data_2', 'manual__2025-05-01T21:16:23.234657+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp6l5wq6kc']
[2025-05-01T21:16:31.384+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask transform_data_2
[2025-05-01T21:16:31.429+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-01T21:16:31.494+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_demo.transform_data_2 manual__2025-05-01T21:16:23.234657+00:00 [running]> on host b3f0d5cbc6df
[2025-05-01T21:16:31.679+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_demo' AIRFLOW_CTX_TASK_ID='transform_data_2' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T21:16:23.234657+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-01T21:16:23.234657+00:00'
[2025-05-01T21:16:31.680+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-01T21:16:31.742+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-01T21:16:31.743+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-01T21:16:31.760+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_pipeline_demo, task_id=transform_data_2, run_id=manual__2025-05-01T21:16:23.234657+00:00, execution_date=20250501T211623, start_date=20250501T211631, end_date=20250501T211631
[2025-05-01T21:16:31.797+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-01T21:16:31.835+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-01T21:16:31.849+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
